
"use client";

import { useState } from 'react';
import { useForm, type SubmitHandler } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { SmartDocsSchema, type SmartDocsInput } from '@/lib/schemas';
import { generateDocumentation, type GenerateDocumentationOutput } from '@/ai/flows/generate-documentation';
import { AppLayout } from '@/components/layout/app-layout';
import { PageHeader } from '@/components/layout/page-header';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { Loader2 } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';


export default function SmartDocsPage() {
  const [generatedDoc, setGeneratedDoc] = useState<GenerateDocumentationOutput | null>(null);
  const [editableDocText, setEditableDocText] = useState<string>('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<SmartDocsInput>({
    resolver: zodResolver(SmartDocsSchema),
    defaultValues: {
      vin: '',
      trailerSpecs: '', // This field's label and placeholder will change based on documentType
      documentType: 'NVIS', 
    },
  });

  const onSubmit: SubmitHandler<SmartDocsInput> = async (data) => {
    setIsLoading(true);
    setGeneratedDoc(null);
    setEditableDocText('');
    try {
      // The generateDocumentation flow now expects documentType in its input object
      const result = await generateDocumentation(data);
      setGeneratedDoc(result);
      setEditableDocText(result.documentText);
      toast({
        title: `${data.documentType} Generated`,
        description: `The ${data.documentType === 'NVIS' ? 'NVIS certificate' : 'Bill of Sale'} has been successfully generated by AI.`,
      });
    } catch (error) {
      console.error("Error generating documentation:", error);
      let errorMessage = "Failed to generate documentation. Please try again.";
      if (error instanceof Error) {
        errorMessage = error.message;
      }
      toast({
        title: "Error Generating Document",
        description: errorMessage,
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleTextChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEditableDocText(e.target.value);
  };

  const handleDownload = () => {
    if (!editableDocText || !generatedDoc) return;

    const selectedDocType = form.getValues('documentType');
    const vin = form.getValues('vin') || 'document';
    const filename = `${selectedDocType}_${vin}.txt`;
    
    const blob = new Blob([editableDocText], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href); // Clean up
    
    toast({
      title: "Download Started",
      description: `${filename} is being downloaded.`,
    });
  };

  const watchedDocumentType = form.watch('documentType');

  return (
    <AppLayout>
      <PageHeader 
        title="Smart Docs: NVIS & Bills of Sale"
        description="AI-powered generation of New Vehicle Information Statements (NVIS) and Bills of Sale."
      />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="font-headline">Document Details</CardTitle>
            <CardDescription className="font-body">Select document type and enter details for AI generation.</CardDescription>
          </CardHeader>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)}>
              <CardContent className="space-y-4">
                <FormField
                  control={form.control}
                  name="documentType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="font-headline">Document Type</FormLabel>
                      <Select 
                        onValueChange={(value) => {
                          field.onChange(value);
                          // Optionally reset trailerSpecs when type changes if desired
                          // form.resetField("trailerSpecs"); 
                        }} 
                        defaultValue={field.value}
                      >
                        <FormControl>
                          <SelectTrigger className="font-body">
                            <SelectValue placeholder="Select document type" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="NVIS" className="font-body">NVIS Certificate</SelectItem>
                          <SelectItem value="BillOfSale" className="font-body">Bill of Sale</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="vin"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="font-headline">Vehicle Identification Number (VIN)</FormLabel>
                      <FormControl>
                        <Input placeholder="Enter 17-character VIN" {...field} className="font-body"/>
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="trailerSpecs" 
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="font-headline">
                        {watchedDocumentType === 'BillOfSale' ? 'Transaction & Vehicle Details' : 'Trailer Specifications'}
                      </FormLabel>
                      <FormControl>
                        <Textarea 
                          placeholder={
                            watchedDocumentType === 'BillOfSale' 
                              ? "e.g., Seller: John Doe, 123 Main St; Buyer: Jane Smith, 456 Oak Ave; Price: $5000; Vehicle: 2023 Utility Trailer. Provide as much detail as possible." 
                              : "e.g., Manufacturer: Acme Trailers, Model: UT-200, GVWR: 7000 lbs, Axles: 2, DOM: 03/2024. Provide comprehensive trailer details."
                          } 
                          {...field} 
                          rows={5} 
                          className="font-body"
                        />
                      </FormControl>
                       <FormDescription className="font-body text-xs">
                        {watchedDocumentType === 'BillOfSale' 
                              ? "Include seller/buyer names & addresses, sale price, date, and key vehicle info." 
                              : "Include manufacturer, model, GVWR, GAWRs, tire/rim specs, manufacture date, etc."}
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
              <CardFooter>
                <Button type="submit" disabled={isLoading} className="w-full">
                  {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                  Generate Document
                </Button>
              </CardFooter>
            </form>
          </Form>
        </Card>

        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="font-headline">Generated Document</CardTitle>
            <CardDescription className="font-body">Preview and edit the AI-generated document below. You can download it once generated.</CardDescription>
          </CardHeader>
          <CardContent>
            {isLoading && (
              <div className="flex flex-col justify-center items-center h-60">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="font-body mt-2">Generating document...</p>
              </div>
            )}
            {!isLoading && generatedDoc && (
              <Textarea
                value={editableDocText}
                onChange={handleTextChange}
                rows={15}
                className="font-body w-full p-3 border rounded-md bg-background shadow-inner"
                placeholder="Generated document will appear here..."
              />
            )}
            {!isLoading && !generatedDoc && (
              <div className="text-center text-muted-foreground font-body p-4 border border-dashed rounded-md h-60 flex items-center justify-center">
                Your AI-generated NVIS or Bill of Sale will appear here after submitting the details.
              </div>
            )}
          </CardContent>
          {generatedDoc && !isLoading && (
            <CardFooter>
               <Button 
                  variant="outline" 
                  className="w-full" 
                  onClick={handleDownload} 
                  disabled={!editableDocText}
                >
                Download Document
              </Button>
            </CardFooter>
          )}
        </Card>
      </div>
    </AppLayout>
  );
}

