
"use client";

import type { CheckComplianceOutput } from '@/ai/flows/check-compliance-flow';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Loader2, ShieldCheck, AlertTriangle, CheckCircle2, ShieldAlert } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

interface ComplianceReportProps {
  result: CheckComplianceOutput | null;
  isLoading: boolean;
}

const StatusIconMap: Record<string, React.ReactNode> = {
  "Compliant": <CheckCircle2 className="w-7 h-7 text-success mr-2" />,
  "Potential Issues": <AlertTriangle className="w-7 h-7 text-warning mr-2" />,
  "Non-Compliant": <ShieldAlert className="w-7 h-7 text-destructive mr-2" />,
};

const getStatusIcon = (status?: string): React.ReactNode => {
    if (!status) {
      return <ShieldCheck className="w-7 h-7 text-muted-foreground mr-2" />; // Initial state
    }
    return StatusIconMap[status] || <ShieldCheck className="w-7 h-7 text-primary mr-2" />; // Default/fallback
};

export default function ComplianceReport({ result, isLoading }: ComplianceReportProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-headline flex items-center">
          {getStatusIcon(result?.complianceStatus)}
          Compliance Report
        </CardTitle>
        <CardDescription className="font-body">AI-generated compliance analysis and recommendations.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {isLoading && (
          <div className="flex flex-col justify-center items-center h-60">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="font-body mt-2">Analyzing compliance...</p>
          </div>
        )}
        {!isLoading && result && (
          <div className="space-y-4">
            <div>
              <h4 className="font-headline text-lg text-primary">Overall Status</h4>
              <p className="font-body text-md font-semibold p-2 bg-muted/30 rounded-md border">
                {result.complianceStatus}
              </p>
            </div>
            <div>
              <h4 className="font-headline text-lg text-primary">Summary</h4>
              <p className="font-body text-sm bg-muted/30 p-3 rounded-md border whitespace-pre-wrap">
                {result.summary}
              </p>
            </div>
            <div>
              <h4 className="font-headline text-lg text-primary">Detailed Findings</h4>
              {result.findings && result.findings.length > 0 ? (
                <Accordion type="single" collapsible className="w-full">
                  {result.findings.map((finding, index) => (
                    <AccordionItem value={`item-${index}`} key={index}>
                      <AccordionTrigger className="text-left hover:no-underline">
                        <div className="flex items-start gap-3">
                          {finding.isCritical && <ShieldAlert className="w-6 h-6 text-destructive shrink-0 mt-1" />}
                          <span className="font-semibold">{finding.issue}</span>
                        </div>
                      </AccordionTrigger>
                      <AccordionContent className="text-muted-foreground pl-9">
                          <p className="font-bold text-foreground mb-2">Recommendation:</p>
                          <p>{finding.recommendation}</p>
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              ) : (
                <div className="text-center text-success font-body p-4 border border-dashed border-success/50 rounded-md h-40 flex flex-col items-center justify-center bg-success/10 mt-2">
                    <CheckCircle2 className="w-12 h-12 text-success mb-4" />
                    <p className="font-semibold">No compliance issues found!</p>
                    <p className="text-sm text-muted-foreground">The document appears to be compliant based on the provided regulations.</p>
                </div>
              )}
            </div>
            <Alert className="mt-6 text-xs">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle className="font-bold">Disclaimer</AlertTitle>
                <AlertDescription>
                    This compliance analysis is generated by an AI for informational purposes only and does not constitute legal advice. Please consult with a qualified professional to ensure full compliance with all applicable laws and regulations.
                </AlertDescription>
            </Alert>
          </div>
        )}
        {!isLoading && !result && (
          <div className="text-center text-muted-foreground font-body p-4 border border-dashed rounded-md h-60 flex flex-col items-center justify-center">
            <ShieldCheck className="w-12 h-12 text-muted-foreground/50 mb-4" />
            <p>Your compliance report will appear here once you submit the form.</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
